### PR TITLE
Removed ROOT_DIR arg

### PR DESCRIPTION
**Pull request by thatzopoulos**
Removed ROOT_DIR as an arg from all subcommands and set its value to always be "."

### CODE REVIEW

**Review by rtwalker — APPROVED** [review]

**Review by Smittyvb — APPROVED** [review]

**Review by epgts — APPROVED** [review]
Can we just drop ROOT_DIR entirely?

Thanks!

**Comment by thatzopoulos** [comment]
> Can we just drop ROOT_DIR entirely?
> 
> Thanks!

Removed root_dir arg from the CLI and updated tools/build to not use it anymore

**Comment by epgts** [comment]
> Would you like me to remove it from the internal functions that currently use it as well or is it enough to set it to "." in main.rs?

I think it's fine either way.

Don't forget to squash away the intermediate commit and update the PR description :)

Thanks!

**Pull request merged**
