### PR TITLE
start 1.16.0-dev

### PR DESCRIPTION
**Pull request by svenklemm**

### CODE REVIEW

**Comment by jerryxwu** [comment]
bors+

**Comment by Smittyvb** [comment]
Looks like the upgrade tests failed:

```
tests/update/time-weighted-average.md:45 `Time Weighted Average Tests`::`Test integral and interpolated integral`

SELECT integral(agg, 'hrs') FROM twa;

Error: output has a different values than expected.
Expected
200
 60
550
(3 rows)

Received
625
100
220
(3 rows)

Delta
-200+625
 -60+100
-550+220
```

**Comment by jerryxwu** [comment]
@thatzopoulos Has the behaviour of `integral` and `interpolated_integral` changed at all?

**Comment by WireBaron** [comment]
Resubmitted this as #737

**Pull request closed without merging**
