### PR TITLE
Make next release upgradeable from 1.12.0

### PR DESCRIPTION
**Pull request by rtwalker**
Should have been part of #606

### CODE REVIEW

**Review by epgts — APPROVED** [review]

**Review by epgts — CHANGES_REQUESTED** [review]
uh oh:
E: Version '1:1.12.0~debian11' for 'timescaledb-toolkit-postgresql-14' was not found

**Comment by epgts** [comment]
> uh oh: E: Version '1:1.12.0~debian11' for 'timescaledb-toolkit-postgresql-14' was not found

ahhhh i bet i failed to apt-get update

**Review by WireBaron — APPROVED** [review]
Change looks good once we figure out the test failure

**Comment by epgts** [comment]
> Change looks good once we figure out the test failure

It should just need a rebase.

**Comment by rtwalker** [comment]
> It should just need a rebase.

🤞

**Review by Smittyvb — APPROVED** [review]

**Review by epgts — APPROVED** [review]

**Pull request merged**
