### PR TITLE
We missed a place to update the cargo-pgx version.

### PR DESCRIPTION
**Pull request by epgts**
We really need to get a handle on this...

### CODE REVIEW

**Comment by epgts** [comment]
Why don't we run `.github/workflows/patch_build.yml` on every pull request?
Currently we limit it to
```
    paths:
      - 'docker/patch/**'
      - '.github/workflows/patch_build.yml'
```

but that means we miss breaking changes like the pgx upgrade.

Any change to the inputs to `cargo pgx install` or `cargo run --manifest-path ../tools/post-install/Cargo.toml` need to execute this to detect breakage...  and that's almost everything.

**Review by rtwalker — COMMENTED** [review]
> Apparently when running sql-doctester under patch_build, the extension
needs to be DROPped first.  Make tools/build DROP and switch to that.

From CI error message:
> thread 'main' panicked at 'could not run init script: Error { ... message: "extension \"timescaledb\" does not exist" ... }', tools/sql-doctester/src/runner.rs:102:14

Do you want `DROP EXTENSION IF EXISTS`?

**Comment by rtwalker** [comment]
> We really need to get a handle on this...

Agreed. Thanks for leaving the comment hints in the appropriate places! Wonder what else we can do for this?

**Comment by epgts** [comment]
Well both extensions are definitely already there :(

So I think I have only papered over a problem we need to instead
understand.

But no one needs this to work right now so I am going to file an issue and
leave it broken for now.

Thanks.

**Review by rtwalker — APPROVED** [review]

**Pull request closed without merging**
